
#loglevel = info

[agent]
type = http
rules = ../../../rules/http.rules.yml
server = http://localhost:4003

[props]
port = 5001
apikeyserver = http://localhost:3001
apikeytoken = example-http-api-token
weblog = 
