//
// Copyright (C) 2026, Open Answers Ltd https://www.openanswers.co.uk/
// All rights reserved.
// This file is subject to the terms and conditions defined in the Software License Agreement.
//

process.env.NODE_ENV = 'test';

const { expect } = require('../../mocha_helpers');
const Class = require('joose').Class;
const { Role } = require('../../../lib/utils/agent_role');

// Build a trivial class that does the Role so we can observe the props/eventCB
// getters generated by Joose.
const HostAgent = Class({
  does: [Role],
  has: {},
});

describe('Unit::EventMonitors::utils::AgentRole', function () {
  it('exposes readonly props and eventCB when constructed with both', function () {
    const cb = function () {
      /* noop */
    };
    const a = new HostAgent({ props: { host: 'h1' }, eventCB: cb });

    expect(a.getProps()).to.deep.equal({ host: 'h1' });
    expect(a.getEventCB()).to.equal(cb);
  });

  it('throws when required props is missing', function () {
    expect(function () {
      new HostAgent({ eventCB: function () {} });
    }).to.throw();
  });

  it('throws when required eventCB is missing', function () {
    expect(function () {
      new HostAgent({ props: {} });
    }).to.throw();
  });

  it('exposes a my.getProperties() class-level accessor returning an array', function () {
    expect(HostAgent.getProperties()).to.be.an('array');
  });
});
