# This is an event console config

app:
  name: 'Panther'
  console: 'Default'
  email: 'support@openanswers.co.uk'
  url: 'http://localhost:3001'
  support_url: 'https://openanswers.github.io/panther-docs'
  view_limit: 2000
  admin_account: '_oa_admin'
  assets_build_dir: dist/builtAssets
  private_path: 'private'
  domain: 'localhost'
  client_id: 'local0'
  swagger_docs: false
  key:
    apikey:
      'uuid-blag-uuid': event_monitor_http

  upload:
    maxsize: 32768

  archive_time:
    clear: 72
    delete: 8

  integrations:
    logs:
      hours: 168
      #24 * 7

  syslog_port: 5000

event_server:
  host: localhost
  port: 4003

event_monitors:
  syslogd:
    host: localhost
    port: 1503
  http:
    host: localhost
    port: 5001

mongodb:
  uri: 'mongodb://127.0.0.1:27017/panther'
  database: panther
  collection: 'alerts'
  timer: 12000
  # 2 seconds
  max_connects: 20

http:
  port: 3001
  secure_port: 3002

smtp:
  host: 'mta.example.com'
  port: 25

session:
  secret: '4&lopaa2sdfe1$23z=.14kj343po4[ld[aE;f]fdlka'
  timeout: 172800000
  # ms = 2 * 24 * 60 * 60 * 1000 = 2 days

rules:
  path: '../../rules'
  git: true
  push: false
